map_memory_node:
  ros__parameters:
    global_frame: "sim_world"
    width: 400
    height: 400
    resolution: 0.1
    origin_x: -20.0
    origin_y: -20.0
    update_distance_threshold: 1.5
    publish_period_ms: 1000
